// lotask4j-admin-frontend/src/views/WebEmbedConfigManage.vue
<template>
  <div class="app-page">
    <TitledSection :title="t('embedConfig.title')" icon="ri-stack-line">
      <template #actions>
        <el-button type="primary" :icon="Plus" @click="handleAdd">
          {{ t('embedConfig.addNew') }}
        </el-button>
      </template>
      <WorkSection>
        <el-table v-loading="loading" :data="configs" stripe border>
          <el-table-column :label="t('embedConfig.componentType')" width="140">
            <template #default="{ row }">
              <el-tag :type="componentTagType(row.componentType)" effect="light">
                {{ row.componentType }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column :label="t('embedConfig.configKey')" prop="configKey" min-width="160" />
          <el-table-column :label="t('embedConfig.configName')" prop="configName" min-width="140" />
          <el-table-column :label="t('embedConfig.userId')" prop="userId" width="120" />
          <el-table-column :label="t('embedConfig.mode')" width="100">
            <template #default="{ row }">
              <el-tag :type="row.isOpen ? 'warning' : 'primary'" size="small">
                {{ row.isOpen ? t('embedConfig.open') : t('embedConfig.auth') }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column :label="t('common.enabled')" width="100">
            <template #default="{ row }">
              <el-switch :model-value="row.isEnabled === 1" @change="(v: boolean) => handleToggle(row, v)" />
            </template>
          </el-table-column>
          <el-table-column :label="t('common.action')" width="220" fixed="right">
            <template #default="{ row }">
              <el-button type="primary" size="small" link @click="handlePreview(row)">
                {{ t('embedConfig.preview') }}
              </el-button>
              <el-button type="primary" size="small" link @click="handleEmbed(row)">
                {{ t('embedConfig.embed') }}
              </el-button>
              <el-button type="primary" size="small" link @click="handleEdit(row)">
                {{ t('embedConfig.edit') }}
              </el-button>
              <el-popconfirm
                :title="t('common.deleteConfirm')"
                :confirm-button-text="t('common.confirm')"
                :cancel-button-text="t('common.cancel')"
                @confirm="handleDelete(row)"
              >
                <template #reference>
                  <el-button type="danger" size="small" link>
                    {{ t('common.delete') }}
                  </el-button>
                </template>
              </el-popconfirm>
            </template>
          </el-table-column>
        </el-table>
      </WorkSection>
    </TitledSection>

    <!-- 新建/编辑 -->
    <AppDialog :visible="dialogVisible" @update:visible="dialogVisible = $event"
      :title="editing ? t('embedConfig.edit') : t('embedConfig.addNew')"
      width="640px"
    >
      <el-form ref="formRef" :model="form" :rules="rules" label-width="120px">
        <el-form-item :label="t('embedConfig.componentType')" prop="componentType">
          <el-select v-model="form.componentType" :disabled="!!editing" style="width: 100%">
            <el-option label="task-list" value="task-list" />
            <el-option label="task-detail" value="task-detail" />
            <el-option label="task-card" value="task-card" />
          </el-select>
        </el-form-item>
        <el-form-item :label="t('embedConfig.configKey')" prop="configKey">
          <el-input v-model="form.configKey" :placeholder="t('embedConfig.configKeyPlaceholder')" />
        </el-form-item>
        <el-form-item :label="t('embedConfig.configName')" prop="configName">
          <el-input v-model="form.configName" />
        </el-form-item>
        <el-form-item :label="t('embedConfig.userId')" prop="userId">
          <el-input v-model="form.userId" />
        </el-form-item>
        <el-form-item :label="t('embedConfig.mode')">
          <el-radio-group v-model="form.isOpen">
            <el-radio :value="0">{{ t('embedConfig.auth') }}</el-radio>
            <el-radio :value="1">{{ t('embedConfig.open') }}</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item v-if="!form.isOpen" :label="t('embedConfig.callbackUrl')">
          <el-input v-model="form.callbackUrl" placeholder="https://biz.example.com/auth/verify" />
        </el-form-item>
        <el-form-item :label="t('embedConfig.config')">
          <el-input
            v-model="form.configStr"
            type="textarea"
            :rows="4"
            placeholder='{"task-list": {"theme": "light"}}'
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">{{ t('common.cancel') }}</el-button>
        <el-button type="primary" :loading="submitting" @click="handleSubmit">{{ t('common.confirm') }}</el-button>
      </template>
    </AppDialog>

    <!-- 预览 -->
    <AppDrawer :visible="previewVisible" @update:visible="previewVisible = $event"
      :title="t('embedConfig.preview')"
      width="900px"
    >
      <iframe v-if="previewUrl" :src="previewUrl" class="preview-iframe" />
    </AppDrawer>

    <!-- 嵌入 URL -->
    <AppDrawer :visible="embedVisible" @update:visible="embedVisible = $event"
      :title="t('embedConfig.embed')"
      width="640px"
    >
      <p>{{ t('embedConfig.embedDesc') }}</p>
      <el-input v-model="embedUrl" type="textarea" :rows="3" readonly class="url-input" />
      <el-button type="primary" style="margin-top: 12px" @click="copyEmbedUrl">
        {{ t('embedConfig.copy') }}
      </el-button>
      <h4 style="margin-top: 24px">{{ t('embedConfig.usage') }}</h4>
      <pre class="code-block">&lt;iframe
  src="{{ embedUrl }}"
  width="100%"
  height="800px"
  frameborder="0"
&gt;&lt;/iframe&gt;</pre>
    </AppDrawer>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, reactive } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, type FormInstance } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import {
  listConfigs, getConfig, createConfig, updateConfig, deleteConfig, toggleEnabled, getPreviewUrl,
  type WebEmbedConfig
} from '@/api/embed'
import TitledSection from '@/components/sdk/common/TitledSection.vue'
import WorkSection from '@/components/sdk/common/WorkSection.vue'
import AppDialog from '@/components/sdk/common/AppDialog.vue'
import AppDrawer from '@/components/sdk/common/AppDrawer.vue'

const { t } = useI18n()
const loading = ref(false)
const submitting = ref(false)
const configs = ref<WebEmbedConfig[]>([])

const dialogVisible = ref(false)
const editing = ref<WebEmbedConfig | null>(null)
const formRef = ref<FormInstance>()

const form = reactive({
  id: undefined as number | undefined,
  componentType: 'task-list',
  configKey: '',
  configName: '',
  userId: 'guest',
  isOpen: 1,
  callbackUrl: '',
  configStr: '{}',
})

const rules = {
  componentType: [{ required: true, message: () => t('common.required'), trigger: 'change' }],
  configKey: [{ required: true, message: () => t('common.required'), trigger: 'blur' }],
  configName: [{ required: true, message: () => t('common.required'), trigger: 'blur' }],
  userId: [{ required: true, message: () => t('common.required'), trigger: 'blur' }],
}

async function load() {
  loading.value = true
  try {
    const res = await listConfigs({ page: 1, pageSize: 50 })
    configs.value = res.data.items
  } finally {
    loading.value = false
  }
}

function componentTagType(t: string): 'success' | 'primary' | 'warning' {
  const map: Record<string, 'success' | 'primary' | 'warning'> = {
    'task-list': 'success',
    'task-detail': 'primary',
    'task-card': 'warning'
  }
  return map[t] || 'primary'
}

function handleAdd() {
  editing.value = null
  Object.assign(form, {
    id: undefined,
    componentType: 'task-list',
    configKey: '',
    configName: '',
    userId: 'guest',
    isOpen: 1,
    callbackUrl: '',
    configStr: '{}',
  })
  dialogVisible.value = true
}

async function handleEdit(row: WebEmbedConfig) {
  const res = await getConfig(row.id!)
  Object.assign(form, {
    id: res.data.id,
    componentType: res.data.componentType,
    configKey: res.data.configKey,
    configName: res.data.configName,
    userId: res.data.userId,
    isOpen: res.data.isOpen,
    callbackUrl: res.data.callbackUrl || '',
    configStr: JSON.stringify(res.data.config || {}, null, 2),
  })
  editing.value = res.data
  dialogVisible.value = true
}

async function handleSubmit() {
  if (!formRef.value) return
  await formRef.value.validate()
  submitting.value = true
  try {
    let config: any = {}
    try {
      config = form.configStr ? JSON.parse(form.configStr) : {}
    } catch {
      ElMessage.error(t('embedConfig.configJsonError'))
      return
    }

    const data: any = {
      componentType: form.componentType,
      configKey: form.configKey,
      configName: form.configName,
      userId: form.userId,
      isOpen: form.isOpen,
      callbackUrl: form.isOpen ? undefined : form.callbackUrl,
      config
    }

    if (editing.value?.id) {
      data.id = editing.value.id
      await updateConfig(editing.value.id, data)
    } else {
      await createConfig(data)
    }
    ElMessage.success(t('common.saveSuccess'))
    dialogVisible.value = false
    load()
  } catch (err: any) {
    ElMessage.error(err.message || t('common.saveFailed'))
  } finally {
    submitting.value = false
  }
}

async function handleToggle(row: WebEmbedConfig, v: boolean) {
  try {
    await toggleEnabled(row.id!, v ? 1 : 0)
    ElMessage.success(v ? t('common.saveSuccess') : t('common.disabledSuccess'))
    load()
  } catch (err: any) {
    ElMessage.error(err.message || t('common.operationFailed'))
    load()
  }
}

async function handleDelete(row: WebEmbedConfig) {
  try {
    await deleteConfig(row.id!)
    ElMessage.success(t('common.deleteSuccess'))
    load()
  } catch (err: any) {
    ElMessage.error(err.message || t('common.deleteFailed'))
  }
}

const previewVisible = ref(false)
const previewUrl = ref('')
async function handlePreview(row: WebEmbedConfig) {
  previewVisible.value = true
  try {
    const res = await getPreviewUrl(row.id!, row.componentType)
    previewUrl.value = res.data.url
  } catch (err: any) {
    ElMessage.error(err.message || t('embedConfig.previewUrlFailed'))
  }
}

const embedVisible = ref(false)
const embedUrl = ref('')
async function handleEmbed(row: WebEmbedConfig) {
  embedVisible.value = true
  try {
    const res = await getPreviewUrl(row.id!, row.componentType)
    embedUrl.value = res.data.url
  } catch (err: any) {
    ElMessage.error(err.message || t('embedConfig.urlFailed'))
  }
}

async function copyEmbedUrl() {
  try {
    await navigator.clipboard.writeText(embedUrl.value)
    ElMessage.success(t('embedConfig.copySuccess'))
  } catch {
    ElMessage.error(t('embedConfig.copyFailedManual'))
  }
}

onMounted(load)
</script>

<style scoped lang="scss">
.preview-iframe {
  width: 100%;
  height: calc(100vh - 160px);
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 8px;
}

.url-input {
  font-family: 'SF Mono', Monaco, monospace;
  font-size: 12px;
}

.code-block {
  padding: 12px 0;
  border-top: 1px solid var(--el-border-color-lighter);
  font-size: 12px;
  font-family: 'SF Mono', Monaco, monospace;
  white-space: pre-wrap;
  word-break: break-all;
  margin: 8px 0 0;
}
</style>

// lotask4j-frontend/src/pages/WebEmbedConfigManage.tsx
import { useEffect, useState } from 'react'
import {
  Card,
  Table,
  Button,
  Space,
  Modal,
  Form,
  Input,
  Select,
  Switch,
  message,
  Popconfirm,
  Tag,
  Tabs,
  Drawer
} from 'antd'
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  EyeOutlined,
  ReloadOutlined,
  LinkOutlined
} from '@ant-design/icons'
import {
  listConfigs,
  getConfig,
  createConfig,
  updateConfig,
  deleteConfig,
  toggleEnabled,
  previewUrl,
  type WebEmbedConfig
} from '@services/webEmbedService'

const { TextArea } = Input

export default function WebEmbedConfigManage() {
  const [loading, setLoading] = useState(false)
  const [data, setData] = useState<WebEmbedConfig[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [keyword, setKeyword] = useState('')
  const [isEnabledFilter, setIsEnabledFilter] = useState<number | undefined>()

  // 表单
  const [formModalOpen, setFormModalOpen] = useState(false)
  const [editing, setEditing] = useState<WebEmbedConfig | null>(null)
  const [form] = Form.useForm()

  // 预览 Drawer
  const [previewDrawerOpen, setPreviewDrawerOpen] = useState(false)
  const [previewUrlValue, setPreviewUrlValue] = useState('')

  // 嵌入 URL Drawer
  const [embedUrlDrawerOpen, setEmbedUrlDrawerOpen] = useState(false)
  const [embedUrlValue, setEmbedUrlValue] = useState('')

  async function load() {
    setLoading(true)
    try {
      const res = await listConfigs({ keyword, isEnabled: isEnabledFilter, page, pageSize })
      setData(res.data.items)
      setTotal(res.data.total)
    } catch (err: any) {
      message.error('加载失败: ' + err.message)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load() }, [page, pageSize, keyword, isEnabledFilter])

  function handleAdd() {
    setEditing(null)
    form.resetFields()
    form.setFieldsValue({ isOpen: 0, componentType: 'task-list', config: { 'task-list': { theme: 'light' } } })
    setFormModalOpen(true)
  }

  async function handleEdit(record: WebEmbedConfig) {
    try {
      const res = await getConfig(record.id!)
      setEditing(res.data)
      form.setFieldsValue(res.data)
      setFormModalOpen(true)
    } catch (err: any) {
      message.error('加载详情失败: ' + err.message)
    }
  }

  async function handleSubmit() {
    try {
      const values = await form.validateFields()
      if (editing && editing.id) {
        await updateConfig(editing.id, values)
        message.success('更新成功')
      } else {
        await createConfig(values)
        message.success('创建成功')
      }
      setFormModalOpen(false)
      load()
    } catch (err: any) {
      if (err.errorFields) return
      message.error('操作失败: ' + err.message)
    }
  }

  async function handleDelete(id: number) {
    try {
      await deleteConfig(id)
      message.success('删除成功')
      load()
    } catch (err: any) {
      message.error('删除失败: ' + err.message)
    }
  }

  async function handleToggle(id: number, isEnabled: number) {
    try {
      await toggleEnabled(id, isEnabled)
      message.success(isEnabled === 1 ? '已启用' : '已禁用')
      load()
    } catch (err: any) {
      message.error('操作失败: ' + err.message)
    }
  }

  async function handlePreview(record: WebEmbedConfig) {
    setPreviewDrawerOpen(true)
    try {
      // 预览使用配置的 componentType
      const res = await previewUrl(record.id!, record.componentType)
      setPreviewUrlValue(res.data.url)
    } catch (err: any) {
      message.error('生成预览 URL 失败: ' + err.message)
    }
  }

  async function handleCopyEmbedUrl(record: WebEmbedConfig) {
    try {
      const res = await previewUrl(record.id!, record.componentType)
      setEmbedUrlValue(res.data.url)
      setEmbedUrlDrawerOpen(true)
    } catch (err: any) {
      message.error('生成 URL 失败: ' + err.message)
    }
  }

  return (
    <div style={{ padding: 24 }}>
      <Card>
        <Tabs
          defaultActiveKey="list"
          items={[
            {
              key: 'list',
              label: '配置列表',
              children: (
                <>
                  <Space style={{ marginBottom: 16 }} wrap>
                    <Input.Search
                      placeholder="搜索 configKey / 名称"
                      allowClear
                      style={{ width: 240 }}
                      onSearch={setKeyword}
                    />
                    <Select
                      placeholder="状态筛选"
                      allowClear
                      style={{ width: 120 }}
                      value={isEnabledFilter}
                      onChange={setIsEnabledFilter}
                      options={[
                        { label: '启用', value: 1 },
                        { label: '禁用', value: 0 }
                      ]}
                    />
                    <Button icon={<ReloadOutlined />} onClick={load}>刷新</Button>
                    <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
                      新建配置
                    </Button>
                  </Space>

                  <Table
                    rowKey="id"
                    loading={loading}
                    dataSource={data}
                    pagination={{
                      current: page,
                      pageSize,
                      total,
                      showSizeChanger: true,
                      onChange: (p, ps) => { setPage(p); setPageSize(ps) }
                    }}
                    columns={[
                      { title: 'ID', dataIndex: 'id', width: 80 },
                      {
                        title: '前端组件',
                        dataIndex: 'componentType',
                        width: 140,
                        render: (v: string) => {
                          const colors: Record<string, string> = {
                            'task-list': 'green',
                            'task-detail': 'blue',
                            'task-card': 'purple'
                          }
                          return <Tag color={colors[v] || 'default'}>{v}</Tag>
                        }
                      },
                      { title: 'configKey', dataIndex: 'configKey', width: 160 },
                      { title: '名称', dataIndex: 'configName', width: 160 },
                      { title: 'userId', dataIndex: 'userId', width: 140 },
                      {
                        title: '模式',
                        dataIndex: 'isOpen',
                        width: 100,
                        render: (v: number) => v === 1
                          ? <Tag color="orange">开放</Tag>
                          : <Tag color="blue">鉴权</Tag>
                      },
                      {
                        title: '回调地址',
                        dataIndex: 'callbackUrl',
                        ellipsis: true,
                        render: (v: string) => v || <span style={{ color: '#999' }}>-</span>
                      },
                      {
                        title: '状态',
                        dataIndex: 'isEnabled',
                        width: 100,
                        render: (v: number, r: WebEmbedConfig) => (
                          <Switch
                            checked={v === 1}
                            onChange={(c) => handleToggle(r.id!, c ? 1 : 0)}
                          />
                        )
                      },
                      { title: '创建时间', dataIndex: 'createdAt', width: 170 },
                      {
                        title: '操作',
                        width: 240,
                        fixed: 'right',
                        render: (_: any, r: WebEmbedConfig) => (
                          <Space size="small">
                            <Button type="link" size="small" icon={<EyeOutlined />} onClick={() => handlePreview(r)}>
                              预览
                            </Button>
                            <Button type="link" size="small" icon={<LinkOutlined />} onClick={() => handleCopyEmbedUrl(r)}>
                              嵌入
                            </Button>
                            <Button type="link" size="small" icon={<EditOutlined />} onClick={() => handleEdit(r)}>
                              编辑
                            </Button>
                            <Popconfirm
                              title="确认删除？"
                              onConfirm={() => handleDelete(r.id!)}
                            >
                              <Button type="link" size="small" danger icon={<DeleteOutlined />}>
                                删除
                              </Button>
                            </Popconfirm>
                          </Space>
                        )
                      }
                    ]}
                  />
                </>
              )
            }
          ]}
        />
      </Card>

      {/* 新建/编辑表单 */}
      <Modal
        title={editing ? '编辑配置' : '新建配置'}
        open={formModalOpen}
        onCancel={() => setFormModalOpen(false)}
        onOk={handleSubmit}
        width={720}
        destroyOnClose
      >
        <Form form={form} layout="vertical">
          <Form.Item name="configKey" label="configKey" rules={[{ required: true, max: 64 }]}>
            <Input placeholder="唯一标识" />
          </Form.Item>
          <Form.Item name="configName" label="配置名称" rules={[{ required: true, max: 128 }]}>
            <Input placeholder="业务系统 A" />
          </Form.Item>
          <Form.Item name="userId" label="默认 userId" rules={[{ required: true, max: 64 }]}>
            <Input placeholder="userId" />
          </Form.Item>
          <Form.Item name="isOpen" label="模式">
            <Select
              options={[
                { label: '鉴权模式（需要回调验证）', value: 0 },
                { label: '开放模式（无需鉴权）', value: 1 }
              ]}
            />
          </Form.Item>
          <Form.Item name="componentType" label="限定组件" rules={[{ required: true, message: '必填' }]}>
            <Select
              placeholder="选择该配置用于哪个组件"
              options={[
                { label: '任务列表 (task-list)', value: 'task-list' },
                { label: '任务详情 (task-detail)', value: 'task-detail' },
                { label: '任务卡片 (task-card)', value: 'task-card' }
              ]}
            />
          </Form.Item>
          <Form.Item name="callbackUrl" label="回调地址（鉴权模式必填）">
            <Input placeholder="https://biz.example.com/auth/verify" />
          </Form.Item>
          <Form.Item name="allowedDomains" label="允许的域名">
            <Input placeholder="https://example.com,https://app.example.com" />
          </Form.Item>
          <Form.Item name="config" label="组件配置 (JSON)">
            <TextArea
              rows={6}
              placeholder='{"task-list": {"theme": "light"}}'
              style={{ fontFamily: 'monospace' }}
            />
          </Form.Item>
        </Form>
      </Modal>

      {/* 预览 Drawer */}
      <Drawer
        title="嵌入预览"
        open={previewDrawerOpen}
        onClose={() => setPreviewDrawerOpen(false)}
        width={900}
      >
        {previewUrlValue && (
          <iframe
            src={previewUrlValue}
            style={{ width: '100%', height: 'calc(100vh - 130px)', border: '1px solid #d9d9d9' }}
          />
        )}
      </Drawer>

      {/* 嵌入 URL Drawer */}
      <Drawer
        title="嵌入 URL"
        open={embedUrlDrawerOpen}
        onClose={() => setEmbedUrlDrawerOpen(false)}
        width={720}
      >
        <p style={{ marginBottom: 12, color: '#666' }}>
          复制以下 URL 到业务方系统中即可嵌入：
        </p>
        <Input.TextArea
          value={embedUrlValue}
          rows={4}
          readOnly
          style={{ fontFamily: 'monospace' }}
        />
        <Button
          type="primary"
          style={{ marginTop: 12 }}
          onClick={() => {
            navigator.clipboard.writeText(embedUrlValue)
            message.success('已复制')
          }}
        >
          复制 URL
        </Button>
        <h4 style={{ marginTop: 24 }}>使用示例：</h4>
        <pre style={{ background: '#f5f5f5', padding: 12, borderRadius: 8 }}>
{`<iframe
  src="${embedUrlValue}"
  width="100%"
  height="800px"
  frameborder="0"
></iframe>`}
        </pre>
      </Drawer>
    </div>
  )
}
